# Generated by Django 4.2.3 on 2023-10-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latt', models.CharField(max_length=128)),
                ('long', models.CharField(max_length=128)),
            ],
        ),
    ]
